Repository sparkdotfi/spark-gov-relay, pull requests merged in 2024-06, with the labels that each got.

#15 [SC-429] Remove min and max delay
  src/executors/AuthBridgeExecutor.sol
  src/executors/BridgeExecutorBase.sol
  src/interfaces/IExecutorBase.sol
  test/ArbitrumOneCrosschainTest.t.sol
  test/AuthBridgeExecutor.t.sol
  test/BaseChainCrosschainTest.t.sol
  test/CrosschainTestBase.sol
  test/GnosisCrosschainTest.t.sol
  test/OptimismCrosschainTest.t.sol
  test/mocks/ReconfigurationPayload.sol
Labels: Status: Ready for Review, Priority: High

#16 [SC-428] Remove bridge role
  src/executors/AuthBridgeExecutor.sol
  test/ArbitrumOneCrosschainTest.t.sol
  test/AuthBridgeExecutor.t.sol
  test/BaseChainCrosschainTest.t.sol
  test/GnosisCrosschainTest.t.sol
  test/OptimismCrosschainTest.t.sol
Labels: Status: Ready for Review, Priority: High

#17 [SC-430] Revert on non-existent contract instead of silent success
  src/executors/BridgeExecutorBase.sol
  src/interfaces/IExecutorBase.sol
  test/AuthBridgeExecutor.t.sol
Labels: Status: Ready for Review, Priority: High

#20 [SC-472] Move everything to AccessControl roles
  src/Executor.sol
  src/interfaces/IExecutor.sol
  test/ArbitrumOneCrosschainTest.t.sol
  test/BaseChainCrosschainTest.t.sol
  test/CrosschainTestBase.sol
  test/Executor.t.sol
  test/GnosisCrosschainTest.t.sol
  test/OptimismCrosschainTest.t.sol
  test/mocks/ReconfigurationPayload.sol
Labels: Status: Ready for Review, Priority: High

#19 [SC-463] Refactor to simplify into 1 contract and interface
  README.md
  src/Executor.sol
  src/executors/AuthBridgeExecutor.sol
  src/interfaces/IAuthBridgeExecutor.sol
  src/interfaces/IExecutor.sol
  test/ArbitrumOneCrosschainTest.t.sol
  test/BaseChainCrosschainTest.t.sol
  test/CrosschainTestBase.sol
  test/Executor.t.sol
  test/GnosisCrosschainTest.t.sol
  test/OptimismCrosschainTest.t.sol
  test/mocks/ReconfigurationPayload.sol
Labels: Status: Approved, Priority: High

#21 formatting: First round of cleanup
  src/Executor.sol
  src/interfaces/IExecutor.sol
  test/CrosschainTestBase.sol
  test/Executor.t.sol
Labels: Status: Ready for Review, Priority: Medium
